// Renders an ace site.config.json into a single self-contained HTML file.
//
// Layout ported from the hand-tuned BME804 reference:
//   - sticky header with title, progress pill, search, quiz jump, help, theme toggle
//   - shell grid: sidebar (collapsible on mobile) + main
//   - sidebar: groups per section with sub-topic sub-links, active-state tracking
//   - search palette, help overlay, side-backdrop for mobile — DOM lives in HTML,
//     behavior lives in runtime.js inlined as a <script>.

import { validate, siteConfigSchema, widgetTypes } from "@ace/components";
import { runtimeScript } from "./runtime.js";

export function renderSite(config, opts = {}) {
  const result = validate(config, siteConfigSchema);
  if (!result.valid) {
    throw new Error("Invalid site.config.json:\n  " + result.errors.join("\n  "));
  }

  // Pre-flight: every widget type must be in the registry
  for (const section of config.sections) {
    const widgets = collectWidgets(section);
    for (const w of widgets) {
      if (!widgetTypes.includes(w.type)) {
        throw new Error(`Unknown widget type "${w.type}" in section "${section.id}". Known: ${widgetTypes.join(", ")}`);
      }
    }
  }

  // Cache-bust ES module imports so regenerating the site doesn't leave the
  // browser holding the previous module graph. Any unique per-render string
  // works — we use config.meta.generatedAt if present, else current timestamp.
  const cacheBust = encodeURIComponent(config.meta.generatedAt || String(Date.now()));
  const withBust = (url) => url + (url.includes("?") ? "&" : "?") + "v=" + cacheBust;
  const componentsBundleUrl = withBust(opts.componentsBundleUrl || "./ace-components.js");
  const stylesUrl = withBust(opts.stylesUrl || "./ace-styles.css");
  const siteId = config.siteId || slug(config.meta.course + "-" + (config.meta.examDate || ""));
  const metaLine = [escapeHtml(config.meta.course), config.meta.institution ? escapeHtml(config.meta.institution) : "", config.meta.examDate ? `exam ${escapeHtml(config.meta.examDate)}` : ""].filter(Boolean).join(" · ");

  return [
    `<!DOCTYPE html>`,
    `<html lang="en">`,
    `<head>`,
    `  <meta charset="UTF-8">`,
    `  <meta name="viewport" content="width=device-width, initial-scale=1">`,
    `  <title>${escapeHtml(config.meta.title)}</title>`,
    `  <link rel="stylesheet" href="${escapeHtml(stylesUrl)}">`,
    // KaTeX for math rendering — auto-render picks up $...$ (inline) and $$...$$ (display).
    // Via CDN, not vendored — users who regenerate don't need a build step.
    `  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css" crossorigin="anonymous">`,
    `  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js" crossorigin="anonymous"></script>`,
    `  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js" crossorigin="anonymous" onload="renderMathInElement(document.body, { delimiters: [ {left:'$$',right:'$$',display:true}, {left:'\\\\[',right:'\\\\]',display:true}, {left:'$',right:'$',display:false}, {left:'\\\\(',right:'\\\\)',display:false} ], throwOnError:false, strict:'ignore' });"></script>`,
    `  <style>${renderInlineLayoutCss()}</style>`,
    `</head>`,
    `<body class="ace-root">`,
    `  <header class="ace-top">`,
    `    <div class="ace-top__bar">`,
    `      <button class="ace-menu-btn" id="menuBtn" aria-label="Menu">☰</button>`,
    `      <div class="ace-top__title">${escapeHtml(config.meta.title)}${metaLine ? `<span class="ace-top__sub">${metaLine}</span>` : ""}</div>`,
    `      <div class="ace-top__spacer"></div>`,
    `      <span class="ace-pill" id="progressPill" title="Mastered (click to reset)"><span class="ace-pill__bar"><span id="progressBar"></span></span> <span id="progressTxt"><b>0</b>/0</span></span>`,
    `      <button class="ace-top__btn" id="searchOpen" title="Search (⌘K)"><span>Search</span> <b>⌘K</b></button>`,
    `      <button class="ace-top__btn" id="quizJump" title="Jump to quiz">Quiz</button>`,
    `      <button class="ace-top__btn" id="helpBtn" title="Keyboard shortcuts (?)">?</button>`,
    `      <button class="ace-top__btn" id="themeBtn" title="Toggle theme">☾</button>`,
    `    </div>`,
    `  </header>`,
    `  <div class="ace-side-backdrop" id="sideBackdrop"></div>`,
    `  <div class="ace-shell">`,
    `    <aside class="ace-side" id="side">`,
    config.sections.map((s) => renderSidebarGroup(s)).join("\n"),
    `    </aside>`,
    `    <main id="main" class="ace-main">`,
    ...config.sections.map((section) => renderSection(section)),
    `      <footer class="ace-footer">Generated by <b>ace-review</b> from lecture PDFs. Site ID: <code>${escapeHtml(siteId)}</code>.</footer>`,
    `    </main>`,
    `  </div>`,
    renderPalette(),
    renderHelp(),
    `  <script type="module">`,
    `    import { registry } from "${escapeJs(componentsBundleUrl)}";`,
    `    const siteId = ${JSON.stringify(siteId)};`,
    `    const widgets = ${JSON.stringify(flattenAllWidgets(config))};`,
    `    for (const w of widgets) {`,
    `      const el = document.getElementById(w.mountId);`,
    `      if (!el) continue;`,
    `      const Cls = registry[w.type];`,
    `      if (!Cls) { el.innerHTML = '<div class="ace-error"><strong>Unknown widget: '+w.type+'</strong></div>'; continue; }`,
    `      new Cls().mount(el, w.props, { siteId });`,
    `    }`,
    `    // Re-run KaTeX on newly mounted prose widgets. The CDN auto-render fired at`,
    `    // page onload, before these widgets existed. Wait for KaTeX to be ready.`,
    `    const tryRender = () => {`,
    `      if (typeof renderMathInElement === 'function') {`,
    `        renderMathInElement(document.body, {`,
    `          delimiters: [ {left:'$$',right:'$$',display:true}, {left:'\\\\[',right:'\\\\]',display:true}, {left:'$',right:'$',display:false}, {left:'\\\\(',right:'\\\\)',display:false} ],`,
    `          throwOnError: false, strict: 'ignore'`,
    `        });`,
    `      } else {`,
    `        setTimeout(tryRender, 100);`,
    `      }`,
    `    };`,
    `    tryRender();`,
    `  </script>`,
    `  <script>${runtimeScript()}</script>`,
    `</body>`,
    `</html>`,
  ].join("\n");
}

function renderSidebarGroup(section) {
  const subs = section.subtopics || [];
  const lines = [
    `      <nav class="ace-grp" data-topic="${escapeHtml(section.id)}">`,
    `        <h4><a href="#${escapeHtml(section.id)}">${escapeHtml(section.title)}</a></h4>`,
    ...subs.map((sub) => `        <a href="#${escapeHtml(sub.id)}">${escapeHtml(sub.title)}</a>`),
    `      </nav>`,
  ];
  return lines.join("\n");
}

function renderSection(section) {
  const widgets = section.widgets || [];
  const subtopics = section.subtopics || [];
  const lines = [
    `      <section id="${escapeHtml(section.id)}">`,
    `        <h2>${escapeHtml(section.title)}</h2>`,
    section.summary ? `        <p class="ace-lede">${escapeHtml(section.summary)}</p>` : "",
  ];
  // Flat widgets (if any)
  for (const w of widgets) {
    lines.push(`        <div id="${escapeHtml(mountId(section.id, w.id))}"></div>`);
  }
  // Subtopics (if any)
  for (const sub of subtopics) {
    lines.push(`        <h3 id="${escapeHtml(sub.id)}">${escapeHtml(sub.title)}</h3>`);
    if (sub.summary) lines.push(`        <p class="ace-sub-lede">${escapeHtml(sub.summary)}</p>`);
    for (const w of (sub.widgets || [])) {
      lines.push(`        <div id="${escapeHtml(mountId(section.id, w.id))}"></div>`);
    }
  }
  lines.push(`      </section>`);
  return lines.filter(Boolean).join("\n");
}

function renderPalette() {
  return `
  <div class="ace-palette" id="palette">
    <div class="ace-palette__box" role="dialog" aria-modal="true" aria-label="Search">
      <input id="paletteInput" type="text" placeholder="Search sections, flashcards, quiz questions..." autocomplete="off" spellcheck="false">
      <div class="ace-palette__results" id="paletteResults"></div>
    </div>
  </div>`;
}

function renderHelp() {
  return `
  <div class="ace-help" id="help">
    <div class="ace-help__box" role="dialog" aria-modal="true" aria-label="Keyboard shortcuts">
      <h4>Keyboard shortcuts</h4>
      <dl>
        <dt>⌘K</dt><dd>Open search</dd>
        <dt>/</dt><dd>Open search</dd>
        <dt>?</dt><dd>Toggle this help</dd>
        <dt>Esc</dt><dd>Close search / help</dd>
        <dt>↑ ↓</dt><dd>Navigate search results</dd>
        <dt>Enter</dt><dd>Jump to selected result</dd>
      </dl>
      <div class="ace-help__foot">Click outside or press Esc to close.</div>
    </div>
  </div>`;
}

function renderInlineLayoutCss() {
  return `
*{box-sizing:border-box}
html,body{margin:0;padding:0;background:var(--ace-paper);color:var(--ace-ink)}
body{font-family:var(--ace-serif);font-size:clamp(15px,0.9vw + 12px,17px);line-height:1.65;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
img,svg,canvas,video{max-width:100%;height:auto}
a{color:var(--ace-accent);text-decoration:none}
a:hover{text-decoration:underline;text-underline-offset:3px}

/* Header */
.ace-top{position:sticky;top:0;z-index:40;background:color-mix(in oklab,var(--ace-paper) 94%,transparent);backdrop-filter:blur(8px);border-bottom:1px solid var(--ace-rule)}
.ace-top__bar{max-width:1500px;margin:0 auto;padding:12px clamp(16px,2.4vw,28px);display:flex;align-items:center;gap:clamp(6px,0.8vw,10px);font-family:var(--ace-sans);flex-wrap:nowrap}
.ace-top__title{font-family:var(--ace-sans);font-size:14px;font-weight:600;letter-spacing:.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}
.ace-top__title .ace-top__sub{color:var(--ace-muted);font-weight:400;margin-left:6px}
.ace-top__spacer{flex:1;min-width:0}
.ace-top__btn,.ace-pill{font-family:var(--ace-sans);font-size:13px;background:transparent;border:1px solid var(--ace-rule);color:var(--ace-ink);padding:0 12px;border-radius:6px;cursor:pointer;height:32px;min-width:56px;display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;white-space:nowrap;flex-shrink:0}
.ace-top__btn:hover{border-color:var(--ace-ink)}
.ace-pill{gap:8px;color:var(--ace-muted);border-radius:999px;padding:0 12px}
.ace-pill b{color:var(--ace-accent);font-weight:600}
.ace-pill__bar{display:inline-block;width:60px;height:4px;background:var(--ace-rule);border-radius:999px;overflow:hidden}
.ace-pill__bar span{display:block;height:100%;width:0;background:var(--ace-accent);transition:width .3s}
#searchOpen b{font-family:var(--ace-mono);font-weight:500;font-size:12px;color:var(--ace-muted);margin-left:8px}
.ace-menu-btn{display:none!important;min-width:40px;padding:0 10px;font-family:var(--ace-sans);font-size:16px;background:transparent;border:1px solid var(--ace-rule);color:var(--ace-ink);border-radius:6px;cursor:pointer;height:32px;align-items:center;justify-content:center}
@media(max-width:900px){.ace-menu-btn{display:inline-flex!important}.ace-top__title .ace-top__sub{display:none}#progressPill{display:none}}
@media(max-width:720px){#searchOpen span{display:none}#searchOpen{min-width:40px;padding:0 8px}}
@media(max-width:520px){#helpBtn{display:none}.ace-top__bar{gap:6px;padding:10px 12px}.ace-top__btn{min-width:44px;padding:0 8px;font-size:12.5px}}

/* Shell grid */
.ace-shell{display:grid;grid-template-columns:clamp(200px,18vw,260px) minmax(0,1fr);max-width:1500px;margin:0 auto}
@media(max-width:900px){.ace-shell{grid-template-columns:1fr}}

/* Sidebar */
.ace-side{position:sticky;top:53px;align-self:start;max-height:calc(100vh - 53px);overflow:auto;padding:clamp(16px,2vw,28px) clamp(12px,1.4vw,20px) 60px clamp(14px,1.6vw,24px);font-family:var(--ace-sans);font-size:clamp(12.5px,0.8vw + 8px,13.5px);border-right:1px solid var(--ace-rule)}
.ace-side .ace-grp{margin:2px 0 10px}
.ace-side .ace-grp h4{margin:14px 0 2px;font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:600}
.ace-side .ace-grp h4 a{display:block;padding:5px 8px;border-radius:5px;color:var(--ace-muted);text-decoration:none;line-height:1.4}
.ace-side .ace-grp h4 a:hover{color:var(--ace-ink);background:var(--ace-accent-soft)}
.ace-side .ace-grp.is-active h4 a{color:var(--ace-accent)}
/* Sub-links are rendered but collapsed by default. max-height + opacity animate open when parent .is-active. */
.ace-side .ace-grp > a{display:block;padding:0 8px 0 18px;border-radius:4px;color:var(--ace-ink);line-height:1.45;font-size:13px;text-decoration:none;overflow:hidden;opacity:0;max-height:0;transition:opacity .18s ease,max-height .24s ease,padding .18s ease,color .15s ease,background .15s ease}
.ace-side .ace-grp.is-active > a{opacity:1;max-height:44px;padding-top:5px;padding-bottom:5px}
.ace-side .ace-grp > a:hover{background:var(--ace-accent-soft);text-decoration:none}
.ace-side .ace-grp > a.is-active{color:var(--ace-accent);font-weight:600}
@media(max-width:900px){
  .ace-side{position:fixed;top:0;left:0;bottom:0;width:min(86vw,320px);max-height:none;z-index:51;background:var(--ace-paper);padding:20px 20px 60px;overflow:auto;border-right:1px solid var(--ace-rule);transform:translateX(-100%);transition:transform .22s ease;box-shadow:0 10px 40px rgba(0,0,0,.18)}
  .ace-side.open{transform:translateX(0)}
  .ace-side-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.4);z-index:50;opacity:0;pointer-events:none;transition:opacity .22s ease}
  .ace-side-backdrop.open{opacity:1;pointer-events:auto}
}
.ace-side-backdrop{display:none}
@media(max-width:900px){.ace-side-backdrop{display:block}}

/* Main */
.ace-main{padding:clamp(18px,2vw,28px) clamp(16px,4vw,80px) clamp(60px,8vw,120px);min-width:0}
.ace-main > section{margin:8px 0 36px;scroll-margin-top:64px}
.ace-main h1{font-family:var(--ace-sans);font-weight:700;font-size:clamp(22px,1.6vw + 14px,32px);letter-spacing:-.01em;margin:0 0 8px;line-height:1.2}
.ace-main h2{font-family:var(--ace-sans);font-weight:700;font-size:clamp(18px,0.8vw + 14px,22px);letter-spacing:-.01em;margin:20px 0 10px;padding-top:18px;border-top:1px solid var(--ace-rule);line-height:1.25}
.ace-main h3{font-family:var(--ace-sans);font-weight:600;font-size:clamp(15px,0.3vw + 14px,16px);margin:24px 0 6px;line-height:1.3;scroll-margin-top:64px}
.ace-main section:first-of-type > h2:first-child,.ace-main section > h2:first-child{margin-top:0;padding-top:0;border-top:none}
.ace-main .ace-lede{color:var(--ace-muted);margin:2px 0 14px;max-width:68ch;font-size:15.5px}
.ace-main .ace-sub-lede{color:var(--ace-muted);margin:2px 0 10px;max-width:68ch;font-size:14px}
.ace-footer{max-width:92ch;margin-top:80px;padding-top:18px;border-top:1px solid var(--ace-rule);color:var(--ace-muted);font-size:13px;font-family:var(--ace-sans)}
.ace-footer code{font-family:var(--ace-mono);font-size:12px;color:var(--ace-ink)}

/* Search palette */
.ace-palette{position:fixed;inset:0;background:rgba(20,15,8,.35);z-index:100;display:none;align-items:flex-start;justify-content:center;padding-top:14vh}
.ace-palette.open{display:flex}
.ace-palette__box{background:var(--ace-paper);border:1px solid var(--ace-rule);border-radius:10px;width:min(640px,92vw);max-height:70vh;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 80px rgba(0,0,0,.2)}
.ace-palette input{width:100%;padding:16px 18px;border:none;outline:none;background:transparent;color:var(--ace-ink);font:500 16px var(--ace-sans);border-bottom:1px solid var(--ace-rule)}
.ace-palette__results{overflow:auto;font-family:var(--ace-sans);font-size:14px}
.ace-palette__results a{display:block;padding:10px 18px;color:var(--ace-ink);border-bottom:1px solid var(--ace-rule);text-decoration:none}
.ace-palette__results a:hover,.ace-palette__results a.is-sel{background:var(--ace-accent-soft);text-decoration:none}
.ace-palette__tag{color:var(--ace-muted);font-size:12px;margin-right:8px;text-transform:uppercase;letter-spacing:.04em}
.ace-palette__snip{color:var(--ace-muted);font-size:12.5px;margin-top:2px;line-height:1.45}
.ace-palette em{background:var(--ace-mark);color:var(--ace-ink);font-style:normal;padding:0 1px;border-radius:2px}
.ace-palette__empty{padding:20px;color:var(--ace-muted);text-align:center}

/* Help overlay */
.ace-help{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:200;display:none;align-items:center;justify-content:center}
.ace-help.open{display:flex}
.ace-help__box{background:var(--ace-paper);border:1px solid var(--ace-rule);border-radius:10px;padding:24px 28px;max-width:460px;font-family:var(--ace-sans);font-size:13.5px;box-shadow:0 30px 80px rgba(0,0,0,.25)}
.ace-help__box h4{margin:0 0 14px;font-size:15px;font-family:var(--ace-sans)}
.ace-help__box dl{margin:0;display:grid;grid-template-columns:auto 1fr;gap:8px 14px;color:var(--ace-ink)}
.ace-help__box dt{font-family:var(--ace-mono);font-size:12px;background:var(--ace-accent-soft);padding:2px 8px;border-radius:4px;border:1px solid var(--ace-rule);align-self:start;white-space:nowrap}
.ace-help__box dd{margin:0;color:var(--ace-muted);font-size:13px}
.ace-help__foot{margin-top:16px;font-size:12px;color:var(--ace-muted);text-align:right}
`;
}

// ---- helpers ----

function collectWidgets(section) {
  const widgets = [];
  if (Array.isArray(section.widgets)) widgets.push(...section.widgets);
  if (Array.isArray(section.subtopics)) {
    for (const sub of section.subtopics) {
      if (Array.isArray(sub.widgets)) widgets.push(...sub.widgets);
    }
  }
  return widgets;
}

function flattenAllWidgets(config) {
  const out = [];
  for (const s of config.sections) {
    for (const w of collectWidgets(s)) {
      out.push({ mountId: mountId(s.id, w.id), type: w.type, props: { ...w.props, id: w.id } });
    }
  }
  return out;
}

function mountId(sectionId, widgetId) { return `ace-${sectionId}-${widgetId}`; }
function slug(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "site"; }
function escapeHtml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function escapeJs(s) { return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"'); }
